name: Build

on:
  push:
    branches: [ "develop" ]
  #pull_request:
  #  branches: [ "develop" ]

env:
  SOLUTION_FILE_PATH: .\ShareX.sln

permissions:
  contents: read

jobs:
  build:
    name: Build ShareX
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Release
          - Debug
          - Steam
          - MicrosoftStore
        platform:
          - Any CPU

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Download API keys
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        Invoke-WebRequest "${{ secrets.SECRET_TEST }}" -OutFile "ShareX.UploadersLib\APIKeys\Test.cs"

    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild -m -p:Configuration="${{ matrix.configuration }}" -p:Platform="${{ matrix.platform }}" "${{ env.SOLUTION_FILE_PATH }}"

    - name: Setup
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        & "ShareX.Setup\bin\${{ matrix.configuration }}\ShareX.Setup.exe" -silent -job "${{ matrix.configuration }}"

    - name: Upload artifact (Setup)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
        name: Setup
        path: |
          Output\ShareX-*-setup.exe
          Output\ShareX-*-setup.exe.sha256

    - name: Upload artifact (Portable)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
        name: Portable
        path: |
          Output\ShareX-*-portable.zip
          Output\ShareX-*-portable.zip.sha256

    - name: Upload artifact (Debug)
      if: matrix.configuration == 'Debug'
      uses: actions/upload-artifact@v3
      with:
        name: Debug
        path: |
          Output\ShareX-*-debug.zip
          Output\ShareX-*-debug.zip.sha256

    - name: Upload artifact (Steam)
      if: matrix.configuration == 'Steam'
      uses: actions/upload-artifact@v3
      with:
        name: Steam
        path: |
          Output\ShareX-*-Steam.zip
          Output\ShareX-*-Steam.zip.sha256

    - name: Upload artifact (MicrosoftStore)
      if: matrix.configuration == 'MicrosoftStore'
      uses: actions/upload-artifact@v3
      with:
        name: MicrosoftStore
        path: |
          Output\ShareX-*.appx
          Output\ShareX-*.appx.sha256